// apps/web/src/components/ui/button.tsx
"use client"

import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"
import type { LucideIcon } from "lucide-react"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center rounded-lg border border-transparent bg-clip-padding text-sm font-medium whitespace-nowrap transition-all outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/80",
        outline:
          "border-border bg-background hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:border-input dark:bg-input/30 dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80 aria-expanded:bg-secondary aria-expanded:text-secondary-foreground",
        ghost:
          "hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:hover:bg-muted/50",
        destructive:
          "bg-destructive/10 text-destructive hover:bg-destructive/20 focus-visible:border-destructive/40 focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:hover:bg-destructive/30 dark:focus-visible:ring-destructive/40",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default:
          "h-8 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        xs: "h-6 gap-1 rounded-[min(var(--radius-md),10px)] px-2 text-xs in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-7 gap-1 rounded-[min(var(--radius-md),12px)] px-2.5 text-[0.8rem] in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3.5",
        lg: "h-9 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        icon: "size-8",
        "icon-xs":
          "size-6 rounded-[min(var(--radius-md),10px)] in-data-[slot=button-group]:rounded-lg [&_svg:not([class*='size-'])]:size-3",
        "icon-sm":
          "size-7 rounded-[min(var(--radius-md),12px)] in-data-[slot=button-group]:rounded-lg",
        "icon-lg": "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

const iconSizeMap = {
  xs: 12,
  sm: 14,
  default: 16,
  lg: 18,
  icon: 16,
  "icon-xs": 12,
  "icon-sm": 14,
  "icon-lg": 18,
} as const

interface ButtonProps
  extends ButtonPrimitive.Props,
    VariantProps<typeof buttonVariants> {
  loading?: boolean
  leadingIcon?: LucideIcon
  trailingIcon?: LucideIcon
}

function Button({
  className,
  variant = "default",
  size = "default",
  loading = false,
  leadingIcon: LeadingIcon,
  trailingIcon: TrailingIcon,
  disabled,
  children,
  ...props
}: ButtonProps) {
  const isIconOnly =
    size === "icon" || size === "icon-xs" || size === "icon-sm" || size === "icon-lg"
  const iconSize = iconSizeMap[size ?? "default"]

  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      disabled={disabled || loading}
      {...props}
    >
      {loading ? (
        <>
          <span className="flex items-center justify-center gap-[inherit] opacity-0">
            {LeadingIcon && !isIconOnly && (
              <LeadingIcon size={iconSize} strokeWidth={2} />
            )}
            {children}
            {TrailingIcon && !isIconOnly && (
              <TrailingIcon size={iconSize} strokeWidth={2} />
            )}
          </span>
          <span className="absolute inset-0 flex items-center justify-center">
            <svg className="size-4 animate-spin" viewBox="0 0 24 24" fill="none">
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="3"
              />
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              />
            </svg>
          </span>
        </>
      ) : (
        <>
          {LeadingIcon && !isIconOnly && (
            <LeadingIcon
              size={iconSize}
              strokeWidth={1.75}
              className="transition-[stroke-width] duration-100 group-hover/button:stroke-[2]"
            />
          )}
          {children}
          {TrailingIcon && !isIconOnly && (
            <TrailingIcon
              size={iconSize}
              strokeWidth={1.75}
              className="transition-[stroke-width] duration-100 group-hover/button:stroke-[2]"
            />
          )}
        </>
      )}
    </ButtonPrimitive>
  )
}

export { Button, buttonVariants }
export type { ButtonProps }

// services/sda-frontend/src/lib/components/ui/Button.svelte
<script lang="ts">
    interface Props {
        variant?: 'primary' | 'secondary' | 'danger' | 'ghost';
        size?: 'sm' | 'md' | 'lg';
        disabled?: boolean;
        loading?: boolean;
        type?: 'button' | 'submit' | 'reset';
        onclick?: () => void;
        children: any;
    }

    let {
        variant = 'primary',
        size = 'md',
        disabled = false,
        loading = false,
        type = 'button',
        onclick,
        children,
    }: Props = $props();

    const base = 'inline-flex items-center justify-center gap-2 font-medium rounded-[var(--radius-md)] transition-all duration-150 focus-visible:outline-2 focus-visible:outline-[var(--accent)] disabled:opacity-50 disabled:cursor-not-allowed';

    const variants = {
        primary:   'bg-[var(--accent)] text-white hover:bg-[var(--accent-hover)] active:scale-[0.98]',
        secondary: 'bg-[var(--bg-surface)] border border-[var(--border)] text-[var(--text-muted)] hover:border-[var(--accent)] hover:text-[var(--text)]',
        danger:    'bg-[var(--danger-bg)] border border-[var(--danger)] text-[var(--danger)] hover:bg-[var(--danger)] hover:text-white',
        ghost:     'text-[var(--text-muted)] hover:bg-[var(--bg-hover)] hover:text-[var(--text)]',
    };

    const sizes = {
        sm: 'text-xs px-2.5 py-1.5 h-7',
        md: 'text-sm px-3.5 py-2 h-9',
        lg: 'text-sm px-5 py-2.5 h-11',
    };
</script>

<button
    {type}
    {onclick}
    disabled={disabled || loading}
    class="{base} {variants[variant]} {sizes[size]}"
>
    {#if loading}
        <span class="w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin"></span>
    {/if}
    {@render children()}
</button>
