// _archive/legacy/sda-frontend/src/lib/components/ui/Input.svelte
<script lang="ts">
    interface Props {
        label?: string;
        error?: string;
        type?: string;
        placeholder?: string;
        value?: string;
        name?: string;
        id?: string;
        required?: boolean;
        disabled?: boolean;
        class?: string;
    }

    let {
        label,
        error,
        type = 'text',
        placeholder,
        value = $bindable(''),
        name,
        id,
        required = false,
        disabled = false,
        class: cls = '',
    }: Props = $props();

    const inputId = id ?? name ?? crypto.randomUUID();
</script>

<div class="flex flex-col gap-1 {cls}">
    {#if label}
        <label
            for={inputId}
            class="text-xs font-medium text-[var(--text-muted)]"
        >
            {label}{#if required}<span class="text-[var(--danger)] ml-0.5">*</span>{/if}
        </label>
    {/if}

    <input
        {type}
        {name}
        {placeholder}
        {required}
        {disabled}
        id={inputId}
        bind:value
        class="
            w-full px-3 py-2 text-sm rounded-[var(--radius-md)]
            bg-[var(--bg-surface)] border text-[var(--text)]
            placeholder:text-[var(--text-faint)]
            focus:outline-none focus:ring-2 focus:ring-[var(--accent)] focus:border-[var(--accent)]
            disabled:opacity-50 disabled:cursor-not-allowed
            transition-colors
            {error ? 'border-[var(--danger)]' : 'border-[var(--border)]'}
        "
    />

    {#if error}
        <p class="text-xs text-[var(--danger)]">{error}</p>
    {/if}
</div>

// _archive/web-1.0.x/src/components/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

const Input = React.forwardRef<HTMLInputElement, React.ComponentProps<"input">>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-9 w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring focus-visible:border-accent disabled:cursor-not-allowed disabled:opacity-50 transition-colors",
          className
        )}
        ref={ref}
        {...props}
      />
    )
  }
)
Input.displayName = "Input"

export { Input }
